language: generic
env:
  global:
    - CLI_VERSION=latest
  matrix:
    - BOARD="arduino:avr:nano"
before_install:
  - wget http://downloads.arduino.cc/arduino-cli/arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - tar xf arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - mkdir -p $HOME/bin
  - mv arduino-cli-*-linux64 $HOME/bin/arduino-cli
  - export PATH=$PATH:$HOME/bin
  - arduino-cli core update-index
  - if [[ "$BOARD" =~ "arduino:avr:" ]]; then
      arduino-cli core install arduino:avr;
    fi
  - git clone https://github.com/thomasfredericks/Bounce2 $HOME/Arduino/libraries/Bounce2
  - git clone https://github.com/mrkaleArduinoLib/LiquidCrystal_I2C $HOME/Arduino/libraries/LiquidCrystal_I2C
  - sed -i '43i#include <Wire.h>' $HOME/Arduino/libraries/LiquidCrystal_I2C/src/LiquidCrystal_I2C.h
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
script:
  - arduino-cli compile --verbose --warnings all --fqbn $BOARD $PWD;